### ISSUE TITLE
S01: As an unverified user, I should be able to login with Facebook.

### ISSUE THREAD

**Issue by markmorcos** [mohamed-mehany/Mafqood#15]
The scenario goes as follows: The user clicks on the "Login with Facebook" button, enters their Facebook credentials and authorises the Mafqood Facebook application.  Then, Facebook returns the data to the new action in the sessions controller. There are, then, two cases; if the user was already registered, they get signed in and redirected to the homepage, while if the user didn't register before, they are redirected to the sign up form in which they can edit their name and email, add phone numbers or add addresses, then they click on the "Sign up" button to complete the registration and gets redirected to the homepage.

**Comment by mokhtar93** [comment]
@mohamed-mehany
