### ISSUE TITLE
S09: I should be able to switch languages (English <--> Arabic)

### ISSUE THREAD

**Issue by markmorcos** [mohamed-mehany/Mafqood#34]
A button having an English or Egyptian flag should be added to the layout allowing a user to switch languages.

**Comment by markmorcos** [comment]
@mokhtar93 please review changes in UML
@narimanhesham please review tests

**Comment by narimanhesham** [comment]
@markmorcos 
Your test cases passes and as nourhan said we can ignore methods current_user and authenticate_user!, I'll put the label test reviewed

**Comment by markmorcos** [comment]
@potatoh please review documentation on issue #34 and #35 and add labels when finished
