### ISSUE TITLE
S18: I should be able to view all of my posts

### ISSUE THREAD

**Issue by markmorcos** [mohamed-mehany/Mafqood#35]
A signed in user should be able to view all their submitted posts.  they should be able to view a page having 2 sections; 1 for missing posts and 1 for finding posts with a view similar to the missing/finding/suspect posts index page.

**Comment by mohamed-mehany** [comment]
@markmorcos In users/post.html.haml replace the hard coded loop for finding posts with the render finding_posts

**Comment by mokhtar93** [comment]
put the arrows at the top of each box not in the middle resize the boxes as they should not be all the same size 
 the box of viewing the posts should start later 
the arrow from controller to the model should come after the arrow from to view to the controller not before it @markmorcos

**Comment by narimanhesham** [comment]
@markmorcos Missing user#posts tests
