### ISSUE TITLE
S13: I should be able to report a finding post as mine

### ISSUE THREAD

**Issue by ebramsherif** [mohamed-mehany/Mafqood#36]
Success Demos: The user checks a post of type "finding" and successfully clicks on "report as mine" button

Failure Demos: I am not logged in so I can't see the button

**Comment by ebramsherif** [comment]
@markmorcos Please place code reviewed label here and remove the pending one
@potatoh Please revise all documentation on my FindingPost controller 
@sharkawy94 Please review the scenario
@mokhtar93 Please review the UML and contact me if needed

**Comment by mokhtar93** [comment]
remove the flash
