### ISSUE TITLE
S16: I should be able to edit my finding posts

### ISSUE THREAD

**Issue by ebramsherif** [mohamed-mehany/Mafqood#37]
Success Demos: The user clicks on the "Edit Post" button, a form appears with the already written fields and the user can modify them then clicks "Save" and the post is edited successfully.

Failure Demos: I am not logged in so I can't edit my posts, I am trying to edit someone's else post, I submit missing required data or data in incorrect form

**Comment by ebramsherif** [comment]
@markmorcos Please place code reviewed label here and remove the pending one
@potatoh Please revise all documentation on my FindingPost controller 
@sharkawy94 Please review the scenario
@mokhtar93 Please review the UML and contact me if needed

**Comment by mokhtar93** [comment]
remove the flash

**Comment by sharkawy94** [comment]
@ebramsherif  
- when editing, the image is not attached 
- this message appear in the flash after editing . "t(finding.successful_edit)"

**Comment by ebramsherif** [comment]
@sharkawy94 Why is the scenario reviewed label missing when you've actually reviewed this?
