### ISSUE TITLE
S10: I should be able to create a new verified finding post

### ISSUE THREAD

**Issue by ebramsherif** [mohamed-mehany/Mafqood#4]
Success demo: The user clicks on the "new finding" button. Then, a form appears to the user providing a space to enter the details needed for the finding post. The user enters this data successfully and clicks the "submit" button to save this post.

Failure demo: "I didn't login with FB so I can't view the form or I am seeing the form and entered certain data incorrectly or didn't enter a required field and a descriptive error message appears."

**Comment by mokhtar93** [comment]
@mohamed-mehany
