### ISSUE TITLE
S14: I should be able to report a missing post as found as a verified user

### ISSUE THREAD

**Issue by sharkawy94** [mohamed-mehany/Mafqood#45]
Success demo : The user checks a post of type "missing" and successfully clicks on "report as found" button .
Failure demo : I am not logged in so I can't see the button.

**Comment by mohamed-mehany** [comment]
@sharkawy94 in file missing_posts_controller, the @missing_posts is useles, please remove it, and please fix the indentation for report and please remove the commented line number 18 and change the name to something more descriptive since there are many reports, so maybe report_mine

**Comment by mokhtar93** [comment]
@sharkawy94  for uml remove the box under the user and replace it with dashed line ended with x
the arrow flash should be dotted , move the alt box to the left
