### ISSUE TITLE
S08: i should be able to report

### ISSUE THREAD

**Issue by potatoh** [mohamed-mehany/Mafqood#48]
controller/ model report is required in form int int string.
view in progress

**Comment by potatoh** [comment]
JS buttons are left but you can merge

**Comment by mokhtar93** [comment]
add a new view and put the opt in it 
remove the arrow from the controller to the model and put it at the first of the box 
the arrow from the controller to the view   should be below the arrow before it 
@potatoh

**Comment by sharkawy94** [comment]
@potatoh 
- you were supposed to report spam , fake or duplicates in all posts .
- you just reported spam in finding post .

**Comment by sharkawy94** [comment]
@potatoh 
- still no reports for suspect post 
- all kinds of reports are working in the finding post 
- all kinds of reports are not working in missing post

**Comment by sharkawy94** [comment]
@potatoh 
- error appears while using these buttons in missing posts . (try to change from type to kind)

**Comment by potatoh** [comment]
Check now!

**Comment by potatoh** [comment]
@markmorcos  @ebramsherif  @mohamed-mehany

**Comment by potatoh** [comment]
the branch is S8new
