### ISSUE TITLE
S19: As Admin, I should be able to edit any post(Missing/Finding)

### ISSUE THREAD

**Issue by mohamed-mehany** [mohamed-mehany/Mafqood#65]
Success Demo:
The admin clicks on the "Edit Post" button, a form appears with the all of the post's fields and the admin can modify them then clicks "Save" and the post is edited successfully.  
Failure Demo:
I am not an admin, I submit missing required data or data in incorrect form

**Comment by potatoh** [comment]
where is the doc?
