### ISSUE TITLE
S22: As Admin, I should be able to create other admins

### ISSUE THREAD

**Issue by mohamed-mehany** [mohamed-mehany/Mafqood#66]
Success Demo:
Clicking on "create admin" button in the admin panel by providing a new admin name and password and clicking "create" successfully
Failure Demo:
I am not admin, not in the admin panel, provided alreading existing admin name or wrong password format and display an error message according to the type of failure

**Comment by sharkawy94** [comment]
@mohamed-mehany  i couldn't find the "create admin" button in the admin panel .
