### ISSUE TITLE
S28: Frontend enhancements

### ISSUE THREAD

**Issue by ebramsherif** [mohamed-mehany/Mafqood#69]
Description: Improve the general layout, add dropdown menus for locations, adding images to buttons and adding anything needed to make the UI more mobile friendly

**Comment by ebramsherif** [comment]
@mohamed-mehany please review and merge

**Comment by ebramsherif** [comment]
@mokhtar93 @narimanhesham @potatoh Please remove the labels and place the reviewed label as this story requires no UML, test and documentation reviews. However, you still need to place the labels and remove the pending ones.

@sharkawy94 Please review the scenario

**Comment by sharkawy94** [comment]
@ebramsherif 
- i can't view finding posts .
- when viewing details of missing posts its info is not well ordered and there is no translation for "Age" and for the buttons .

**Comment by ebramsherif** [comment]
@sharkawy94
- It's working be sure to fetch correctly the latest code on branch S28FrontEndEbram
- Re-ordered the data displayed on the missing view grid
- Translations are not a part of this story's scenario, it's an extra I'm doing & with the current grid I think it's impossible
